# Administrace
server {
    server_name admin.<DOMENA>.cz;

    location / {
        proxy_pass http://127.0.0.1:3333;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    listen 443 ssl; 
    ssl_certificate /etc/letsencrypt/live/<DOMENA>.cz/fullchain.pem; 
    ssl_certificate_key /etc/letsencrypt/live/<DOMENA>.cz/privkey.pem; 
    include /etc/letsencrypt/options-ssl-nginx.conf; 
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; 

}

# Phishingové kampaně
server {
    server_name <DOMENA>.cz www.<DOMENA>.cz;

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }


    listen 443 ssl; 
    ssl_certificate /etc/letsencrypt/live/<DOMENA>.cz/fullchain.pem; 
    ssl_certificate_key /etc/letsencrypt/live/<DOMENA>.cz/privkey.pem; 
    include /etc/letsencrypt/options-ssl-nginx.conf; 
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; 


}

server {
    if ($host = www.<DOMENA>.cz) {
        return 301 https://$host$request_uri;
    } 


    if ($host = <DOMENA>.cz) {
        return 301 https://$host$request_uri;
    } 


    listen 80;
    server_name <DOMENA>.cz www.<DOMENA>.cz;
    return 404; 




}
server {
    if ($host = admin.<DOMENA>.cz) {
        return 301 https://$host$request_uri;
    } 


    listen 80;
    server_name admin.<DOMENA>.cz;
    return 404; 


}